### PR TITLE
fix: remove digest check to never ignore helm errors

### LINKED ISSUE #1021: HelmRelease deletion not waiting for `helm uninstall`
### Describe the bug

When you delete a HelmRelease, even with `uninstall.deletionPropagation=foreground`, flux, via helm or otherwise, marks all created resources to be deleted and then removes the finalizer, resulting in the HelmRelease disappearing even though the uninstallation hasn't finished.

This, at least sometimes, leaves the "real" helm release to be stuck in `uninstalling` which has to be manually resolved.

### Steps to reproduce

Create a helm chart like https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/t8s-cluster, which creates CRs that are not just "no-ops" for deletion, like cluster-api resources.

Install it, wait for everything to be ready, uninstall.

### Expected behavior

That flux leaves the finalizer on the HelmRelease until the "real" helm release is really uninstalled.

I suppose what I mean in a non-flux way would be for flux to wait until `helm uninstall` finishes successfully.

### Screenshots and recordings

_No response_

### OS / Distro

N/A

### Flux version

N/A

### Flux check

► checking prerequisites
✗ Kubernetes version v1.27.14 does not match >=1.28.0-0
► checking version in cluster
✔ distribution: flux-2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.38.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.32.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✗ check failed

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

// "moved" from https://github.com/fluxcd/flux2/issues/4872

### PR DESCRIPTION
**Pull request by cwrau**
Closes #1021

### CODE REVIEW

File: internal/reconcile/uninstall.go [hunk 1]
```diff
@@ -138,10 +138,7 @@ func (r *Uninstall) Reconcile(ctx context.Context, req *Request) error {
 	// Handle any error.
 	if err != nil {
 		r.failure(req, logBuf, err)
-		if req.Object.Status.History.Latest().Digest == cur.Digest {
```
Comment (stefanprodan) [inline internal/reconcile/uninstall.go:141]: @cwrau the tests are failing, please run `make test` before opening a PR.

Comment (cwrau) [reply internal/reconcile/uninstall.go:141]: Ok, I thought I didn't understand the code well enough 😅

I don't understand why one wouldn't want to return an error in case of an error, even in this test case. The error is `timed out waiting for the condition`, why not return an error to be retried?

Or rather, why is this working in this case, but not in the case of #1021?

**Comment by cwrau** [comment]
> Hi, I'll help take this forward so that we can include this in the upcoming release.

Amazing, I'm currently struggling with the tests 🙏

**Review by matheuscscp — APPROVED** [review]
> Uninstall is called outside of the AtomicRelease reconciliation. Whenever an object is marked to be deleted or the release target configuration has changed, Uninstall is called directly and the result of Uninstall is taken as it is by the caller, which is mostly the main reconciliation loop. Any error returned by Uninstall is critical to determine the result of it.
In case of UninstallRemediation, it is always called from the atomic reconciliation, which is not strict about the result of the action reconciler. After running an action reconciler, the atomic reconciler separately determines the state of the release to make a decision on the next action. It checks for any failure in the release due to the previous action by analyzing the state of the release in the storage. It doesn't need to depend on the returned error from the UninstallRemediation.

@darkowlzz I can understand (and am OK with) everything before the paragraph above. If you have time, could you please elaborate this part a bit more? Thanks! :pray: 

In any case, LGTM!

Thanks @cwrau and @darkowlzz for working on this!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @darkowlzz and @cwrau

**Comment by cwrau** [comment]
Amazing! Thanks for the help @darkowlzz!
