### PR TITLE
Track changes in `.spec.postRenderers`

### LINKED ISSUE #964: Changes in postRenderers are ingored
Given the below *HelmRelease* with helm-controller v0.37.4:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: '>=6.0.0 <7.0.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1m
      reconcileStrategy: ChartVersion
  upgrade:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: podinfo
                namespace: default
                annotations:
                   hello: world # Changing this line will not trigger an update (unexpected)
  values:
     dummy: x # However, changing this line will trigger an update (expected)
```

# Observed Behavior

Changes to `spec.postRenderers` **will not** trigger an update of the *HelmRelease*. However, changing for example `.spec.values.*` or `spec.chart.spec.*` will trigger an update.  

# Expected Behavior

Changes to `spec.postRenderers` **should** trigger an update of the *HelmRelease*.

### PR DESCRIPTION
**Pull request by souleb**
fix #964

### CODE REVIEW

File: internal/reconcile/state.go [hunk 1]
```diff
@@ -131,6 +131,10 @@ func DetermineReleaseState(ctx context.Context, cfg *action.ConfigFactory, req *
 	case helmrelease.StatusUninstalled:
 		return ReleaseState{Status: ReleaseStatusAbsent, Reason: "found uninstalled release in storage"}, nil
 	case helmrelease.StatusDeployed:
+		//verify if postrender digest has changed
+		if req.PreviousPostrendersDigest != req.Object.Status.LastAttemptedPostRenderersDigest {
```
Comment (stefanprodan) [inline internal/reconcile/state.go:135]: This will trigger an upgrade storm for all releases in a cluster since the `.status.lastAttemptedPostRenderersDigest ` is not present in v2beta2.

File: config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml [hunk 2]
```diff
@@ -3,7 +3,7 @@ apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
   annotations:
-    controller-gen.kubebuilder.io/version: v0.15.0
+    controller-gen.kubebuilder.io/version: v0.14.0
```
Comment (stefanprodan) [inline config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml:6]: Please install controller-gen v0.15.0 on your machine and regenerate

File: internal/controller/helmrelease_controller.go [hunk 3]
```diff
@@ -643,6 +650,9 @@ func (r *HelmReleaseReconciler) adoptLegacyRelease(ctx context.Context, getter g
 	// Erase the last release revision from the status.
 	obj.Status.LastReleaseRevision = 0
 
+	// Set the last attempted post-renderers digest.
+	obj.Status.LastAttemptedPostRenderersDigest = postrender.Digest(digest.Canonical, obj.Spec.PostRenderers).String()
```
Comment (stefanprodan) [inline internal/controller/helmrelease_controller.go:654]: Should we set this if there are no post renderers?

Comment (souleb) [reply internal/controller/helmrelease_controller.go:654]: No, It should be done only if present. Updated

File: internal/controller/helmrelease_controller.go [hunk 4]
```diff
@@ -391,6 +392,13 @@ func (r *HelmReleaseReconciler) reconcileRelease(ctx context.Context, patchHelpe
 	obj.Status.LastAttemptedRevisionDigest = ociDigest
 	obj.Status.LastAttemptedConfigDigest = chartutil.DigestValues(digest.Canonical, values).String()
 	obj.Status.LastAttemptedValuesChecksum = ""
+	// Keep track of the post-renderers digest used during the last reconciliation.
+	// This is used to determine if the post-renderers have changed.
+	oldPostRenderersDigest := obj.Status.LastAttemptedPostRenderersDigest
+	// Update the post-renderers digest with the current post-renderers in the spec.
+	if obj.Spec.PostRenderers != nil {
+		obj.Status.LastAttemptedPostRenderersDigest = postrender.Digest(digest.Canonical, obj.Spec.PostRenderers).String()
+	}
```
Comment (stefanprodan) [inline internal/controller/helmrelease_controller.go:401]: What happens if the previous `PostRenderers` were set but in the current version I remove them?

Comment (souleb) [reply internal/controller/helmrelease_controller.go:401]: As long as it is set, we want to reflect it. We need to keep the logic around the `object` itself in the `reconciler` code. I will push an update shortly.

**Comment by souleb** [comment]
I have tested the last code on a kind cluster with an existing `HR` on `v1beta2`

```yaml
Warning: v2beta2 HelmRelease is deprecated, upgrade to v2
Name:         podinfo-template
Namespace:    default
API Version:  helm.toolkit.fluxcd.io/v2beta2
Kind:         HelmRelease
Metadata:
  Generation:        1
Spec:
  Chart Ref:
    Kind:    HelmChart
    Name:    podinfo
  Interval:  5m
  Post Renderers:
    Kustomize:
      Patches:
        Patch:  - op: add
  path: /metadata/annotations/hello
  value: world2

        Target:
          Kind:     Deployment
          Name:     podinfo-template
          Version:  v1
  Test:
    Enable:  true
  Values:
    Replica Count:  2
Status:
  Conditions:
    Last Transition Time:  2024-05-07T08:23:07Z
    Message:               Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   1
    Reason:                TestSucceeded
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-05-07T08:22:59Z
    Message:               Helm install succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2
    Observed Generation:   1
    Reason:                InstallSucceeded
    Status:                True
    Type:                  Released
    Last Transition Time:  2024-05-07T08:23:07Z
    Message:               Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   1
    Reason:                TestSucceeded
    Status:                True
    Type:                  TestSuccess
  History:
    Chart Name:      podinfo
    Chart Version:   6.6.2
    Config Digest:   sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
    Digest:          sha256:11006d53cba942b73d124414f755869565730d24a36480b3208948c60275597d
    First Deployed:  2024-05-07T08:22:55Z
    Last Deployed:   2024-05-07T08:22:55Z
    Name:            podinfo-template
    Namespace:       default
    Status:          deployed
    Test Hooks:
      podinfo-template-grpc-test-kj0hv:
        Last Completed:  2024-05-07T08:23:02Z
        Last Started:    2024-05-07T08:23:00Z
        Phase:           Succeeded
      Podinfo - Template - Jwt - Test - Gufwh:
        Last Completed:  2024-05-07T08:23:05Z
        Last Started:    2024-05-07T08:23:02Z
        Phase:           Succeeded
      podinfo-template-service-test-aumr6:
        Last Completed:           2024-05-07T08:23:07Z
        Last Started:             2024-05-07T08:23:05Z
        Phase:                    Succeeded
    Version:                      1
  Last Attempted Config Digest:   sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
  Last Attempted Generation:      1
  Last Attempted Release Action:  install
  Last Attempted Revision:        6.6.2
  Observed Generation:            1
  Storage Namespace:              default
Events:
  Type    Reason            Age   From             Message
  ----    ------            ----  ----             -------
  Normal  InstallSucceeded  102s  helm-controller  Helm install succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2
  Normal  TestSucceeded     94s   helm-controller  Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
```
## Existing HelmRelease should adopt PostRenderers status without upgrade

```yaml
Warning: v2beta2 HelmRelease is deprecated, upgrade to v2
Name:         podinfo-template
Namespace:    default
API Version:  helm.toolkit.fluxcd.io/v2beta2
Kind:         HelmRelease
Metadata:
  Generation:        1
Spec:
  Chart Ref:
    Kind:    HelmChart
    Name:    podinfo
  Interval:  5m
  Post Renderers:
    Kustomize:
      Patches:
        Patch:  - op: add
  path: /metadata/annotations/hello
  value: world2

        Target:
          Kind:     Deployment
          Name:     podinfo-template
          Version:  v1
  Test:
    Enable:  true
  Values:
    Replica Count:  2
Status:
  Conditions:
    Last Transition Time:  2024-05-07T08:23:07Z
    Message:               Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   1
    Reason:                TestSucceeded
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-05-07T08:22:59Z
    Message:               Helm install succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2
 1 hr.yaml +                                                                                                                                                                                              X
    Observed Generation:   1
    Reason:                InstallSucceeded
    Status:                True
    Type:                  Released
    Last Transition Time:  2024-05-07T08:23:07Z
    Message:               Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   1
    Reason:                TestSucceeded
    Status:                True
    Type:                  TestSuccess
  History:
    Chart Name:      podinfo
    Chart Version:   6.6.2
    Config Digest:   sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
    Digest:          sha256:11006d53cba942b73d124414f755869565730d24a36480b3208948c60275597d
    First Deployed:  2024-05-07T08:22:55Z
    Last Deployed:   2024-05-07T08:22:55Z
    Name:            podinfo-template
    Namespace:       default
    Status:          deployed
...
    Version:                             1
  Last Attempted Config Digest:          sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
  Last Attempted Generation:             1
  Last Attempted Post Renderers Digest:  sha256:0801f4f2fec3b08c5c25664bbcba357334dfae9aa6f4d59813079749d3acc154
  Last Attempted Release Action:         install
  Last Attempted Revision:               6.6.2
  Last Handled Reconcile At:             2024-05-07T10:24:53.300426+02:00
  Observed Generation:                   1
  Storage Namespace:                     default
```

## Change to PostRenderers should trigger an upgrade

```yaml
Warning: v2beta2 HelmRelease is deprecated, upgrade to v2
Name:         podinfo-template
Namespace:    default
API Version:  helm.toolkit.fluxcd.io/v2beta2
Kind:         HelmRelease
Metadata:
  Generation:        2
Spec:
  Chart Ref:
    Kind:    HelmChart
    Name:    podinfo
  Interval:  5m
  Post Renderers:
    Kustomize:
      Patches:
        Patch:  - op: add
  path: /metadata/annotations/hello
  value: world

        Target:
          Kind:     Deployment
          Name:     podinfo-template
          Version:  v1
  Test:
    Enable:  true
  Values:
    Replica Count:  2
Status:
  Conditions:
    Last Transition Time:  2024-05-07T08:26:38Z
    Message:               Helm test succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   2
    Reason:                TestSucceeded
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-05-07T08:26:20Z
    Message:               Helm upgrade succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2
    Observed Generation:   2
    Reason:                UpgradeSucceeded
    Status:                True
    Type:                  Released
    Last Transition Time:  2024-05-07T08:26:38Z
    Message:               Helm test succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   2
    Reason:                TestSucceeded
    Status:                True
    Type:                  TestSuccess
  ...
  Last Attempted Config Digest:          sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
  Last Attempted Generation:             2
  Last Attempted Post Renderers Digest:  sha256:fd5c051933da29da53f8f5d34c5b89247b88899153b84807cda11b1b9a58f44f
  Last Attempted Release Action:         upgrade
  Last Attempted Revision:               6.6.2
  Last Handled Reconcile At:             2024-05-07T10:26:23.760449+02:00
  Observed Generation:                   2
  Storage Namespace:                     default
Events:
  Type    Reason            Age    From             Message
  ----    ------            ----   ----             -------
  Normal  InstallSucceeded  3m44s  helm-controller  Helm install succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2
  Normal  TestSucceeded     3m36s  helm-controller  Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
  Normal  UpgradeSucceeded  23s    helm-controller  Helm upgrade succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2
  Normal  TestSucceeded     5s     helm-controller  Helm test succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2: 3 test hooks completed successfully
```

## Removing PostRenderers should trigger an update and unset `Last Attempted Post Renderers Digest``

```yaml
Warning: v2beta2 HelmRelease is deprecated, upgrade to v2
Name:         podinfo-template
Namespace:    default
API Version:  helm.toolkit.fluxcd.io/v2beta2
Kind:         HelmRelease
Metadata:
  Generation:        3
Spec:
  Chart Ref:
    Kind:    HelmChart
    Name:    podinfo
  Interval:  5m
  Test:
    Enable:  true
  Values:
    Replica Count:  2
Status:
  Conditions:
    Last Transition Time:  2024-05-07T08:28:04Z
    Message:               Helm test succeeded for release default/podinfo-template.v3 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   3
    Reason:                TestSucceeded
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-05-07T08:27:47Z
    Message:               Helm upgrade succeeded for release default/podinfo-template.v3 with chart podinfo@6.6.2
    Observed Generation:   3
    Reason:                UpgradeSucceeded
    Status:                True
    Type:                  Released
    Last Transition Time:  2024-05-07T08:28:04Z
    Message:               Helm test succeeded for release default/podinfo-template.v3 with chart podinfo@6.6.2: 3 test hooks completed successfully
    Observed Generation:   3
    Reason:                TestSucceeded
    Status:                True
    Type:                  TestSuccess
...
  Last Attempted Config Digest:   sha256:e15c415d62760896bd8bec192a44c5716dc224db9e0fc609b9ac14718f8f9e56
  Last Attempted Generation:      3
  Last Attempted Release Action:  upgrade
  Last Attempted Revision:        6.6.2
  Last Handled Reconcile At:      2024-05-07T10:27:52.283029+02:00
  Observed Generation:            3
  Storage Namespace:              default
Events:
  Type    Reason            Age    From             Message
  ----    ------            ----   ----             -------
  Normal  InstallSucceeded  5m13s  helm-controller  Helm install succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2
  Normal  TestSucceeded     5m5s   helm-controller  Helm test succeeded for release default/podinfo-template.v1 with chart podinfo@6.6.2: 3 test hooks completed successfully
  Normal  UpgradeSucceeded  112s   helm-controller  Helm upgrade succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2
  Normal  TestSucceeded     94s    helm-controller  Helm test succeeded for release default/podinfo-template.v2 with chart podinfo@6.6.2: 3 test hooks completed successfully
  Normal  UpgradeSucceeded  25s    helm-controller  Helm upgrade succeeded for release default/podinfo-template.v3 with chart podinfo@6.6.2
  Normal  TestSucceeded     8s     helm-controller  Helm test succeeded for release default/podinfo-template.v3 with chart podinfo@6.6.2: 3 test hooks completed successfully
```

File: api/v2beta1/helmrelease_types.go [hunk 5]
```diff
@@ -949,6 +949,11 @@ type HelmReleaseStatus struct {
 	// +optional
 	LastAttemptedConfigDigest string `json:"lastAttemptedConfigDigest,omitempty"`
 
+	// LastAttemptedPostRenderersDigest is the digest for the post-renderers of
+	// the last reconciliation attempt.
+	// +optional
+	LastAttemptedPostRenderersDigest string `json:"lastAttemptedPostRenderersDigest,omitempty"`
```
Comment (stefanprodan) [inline api/v2beta1/helmrelease_types.go:955]: Please document this field under https://github.com/fluxcd/helm-controller/blob/main/docs/spec/v2/helmreleases.md#last-attempted-revision-digest

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @souleb 🏅

File: internal/reconcile/reconcile.go [hunk 6]
```diff
@@ -83,6 +83,9 @@ type Request struct {
 	// Values is the Helm chart values to be used for the installation or
 	// upgrade.
 	Values helmchartutil.Values
+	// PreviousPostrendersDigest is the digest of the post-renderers that were used
+	// during the last reconciliation.
+	PreviousPostrendersDigest string
```
[the remark this answers is not in the document]
Comment (souleb) [reply internal/reconcile/reconcile.go]: after discussing the different cases with @darkowlzz, I have updated to what should be a better implementation.
